---
name: Documentation Validation

on:
  push:
    branches: [main]
    paths:
      - "documentation/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "documentation/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate-architecture:
    name: Validate Architecture Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate architecture documents
        uses: embedded-pro/project-documentation@54fca1cb9925af16e53bd9d2640d1285560d295b # v0.2.0
        with:
          run-validate-documents: 'true'
          documents-dir: documentation
          doc-type: architecture

  validate-design:
    name: Validate Design Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate design documents
        uses: embedded-pro/project-documentation@54fca1cb9925af16e53bd9d2640d1285560d295b # v0.2.0
        with:
          run-validate-documents: 'true'
          documents-dir: documentation
          doc-type: design

  validate-theory:
    name: Validate Theory Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate theory documents
        uses: embedded-pro/project-documentation@54fca1cb9925af16e53bd9d2640d1285560d295b # v0.2.0
        with:
          run-validate-documents: 'true'
          documents-dir: documentation
          doc-type: theory
