---
name: Requirements Validation

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate-requirements:
    name: Validate Requirements Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Validate requirements and generate PDF
        uses: embedded-pro/project-documentation@54fca1cb9925af16e53bd9d2640d1285560d295b # v0.2.0
        with:
          run-validate-requirements: 'true'
          run-generate-requirements-pdf: 'true'
          upload-requirements-pdf: 'true'
          schema-path: documentation/tools/requirement.schema.json
          requirements-dir: documentation/requirements
          template-path: documentation/templates/requirements.md
          requirements-pdf-output: documentation/output/requirements.pdf
